/*
   Pron, a wrapper for a ported and somewhat modified Metapron3.

   All Metapron3 copyright (C) 2010 Lawrence Philips.
   Copyright (C) 2018 by Soren Hein for the changes.

   See LICENSE and README.
*/


#include <iostream>
#include <iomanip>
#include <fstream>

#include "Extract.h"
#include "parse.h"


const vector<vector<string>> PartsList =
{
  {"a", "&", "@", "A", "E", "eI", "I", "O", "oU", "U", "-", "E/@", "aI/j/eI", 
    "aI", "h/A", "j/@", "j/A"},
  {"aa", "&", "@", "A", "eI", "O", "oU"},
  {"aaiu", "aI/@"},
  {"ae", "&", "(@)", "@", "A", "aI", "E", "eI", "i", "aI/E", "A/E"},
  {"aea", "i", "i/@"},
  {"aeae", "i/i"},
  {"aeaea", "i/i/@"},
  {"aee", "i/i"},
  {"aei", "eI/I", "i/@", "i/aI", "i/I"},
  {"aejo", "aI/dZ/A"},
  {"aeju", "h/&/dZ/u"},
  {"aeo", "i/oU"},
  {"aeoe", "i/oU/E", "i/oU/I"},
  {"aeoi", "i/Oi"},
  {"aeu", "AU", "i/@"},
  {"aewi", "eI/w/aI"},
  {"aeye", "eI/@"},
  {"ai", "&", "@", "A", "aI", "E", "eI", "i", "j", "A/E", "A/I", "A/i", "eI/I",
    "E/@", "@/I"},
  {"aia", "aI/&", "eI/@", "eI/j", "A/j/@", "aI/@"},
  {"aiae", "eI/i", "eI/j/i"},
  {"aie", "aI/@", "aI/A", "aI/E", "aI/i", "E"},
  {"aieu", "eI/j/u"},
  {"aio", "aI/j/A", "A/j/O"},
  {"aiu", "eI/@"},
  {"aiuo", "aI/w/oU"},
  {"aiwa", "aI/w/A"},
  {"aiwei", "aI/w/eI"},
  {"aiyu", "aI/j/u"},
  {"aiyua", "aI/j/Y/A"},
  {"aj", "@/dZ", "eI", "A", "aI", "&/dZ"},
  {"aja", "@/dZ/&", "@/dZ/@", "A/j/A", "A/h/A", "A/dZ/A", "@/j/@", "@/dZ/A", "aI/@"},
  {"ajaa", "A/j/A"},
  {"ajai", "@/Z/@"},
  {"aje", "&/dZ/@", "&/dZ/I", "@/dZ/E", "A/dZ/@", "A/dZ/E"},
  {"ajee", "A/dZ/i", "@/dZ/i"},
  {"ajeu", "A/Z/y"},
  {"aji", "A/dZ/i", "@/dZ/i", "&/dZ/i"},
  {"ajj", "&/dZ"},
  {"ajji", "&/dZ/i"},
  {"ajo", "@/dZ/@", "@/dZ/A", "@/dZ/O", "@/dz/oU", "@/h/oU", "@/j/oU", "@/Z/O",
    "A/h/O", "A/h/oU", "A/j/O", "eI/dZ/@", "eI/oU"},
  {"ajoie", "&/z/w/A"},
  {"ajou", "@/dZ/u"},
  {"aju", "@/dZ/@", "A/Z/U"},
  {"ajua", "A/w/A"},
  {"ajuo", "aI/w/oU"},
  {"ajuwo", "A/Z/U/w/A"},
  {"ao", "eI/A", "A/oU", "AU", "A/O", "eI/oU", "O", "i/oU"},
  {"aoa", "A/w/A", "AU/A"},
  {"aoe", "eI/i"},
  {"aoi", "AU/I", "eI/i", "eI/I", "i"},
  {"aou", "A/u"},
  {"aoue", "A/w/@"},
  {"aoui", "A/w/i", "O/i"},
  {"au", "&", "@", "A", "AU", "eI", "O", "oU", "u", "A/u"},
  {"aua", "A/w/A"},
  {"aue", "AU/@", "AU"},
  {"auea", "@/w/eI/@"},
  {"auai", "O/aI"},
  {"aui", "AU/i"},
  {"auja", "O/dZ/A"},
  {"aujo", "A/dZ/oU"},
  {"auu", "AU/@"},
  {"auwe", "AU/w/@"},
  {"auwi", "O/w/I"},
  {"auwo", "O/w/U"},
  {"auy", "A/w/I"},
  {"aw", "A", "O"},
  {"awa", "A/w/A", "@/v/A", "@/w/O", "AU/w/@"},
  {"awai", "@/w/eI", "A/w/I"},
  {"awaii", "@/w/aI/i"},
  {"awaiia", "@/w/aI/@"},
  {"away", "@/w/eI"},
  {"awayo", "A/w/A/j/oU"},
  {"awe", "O"},
  {"awea", "@/w/E", "@/w/i"},
  {"awee", "O/i"},
  {"awei", "@/w/eI"},
  {"awi", "A/w/i"},
  {"awie", "Oi"},
  {"awo", "A/w/u"},
  {"awoo", "@/w/U"},
  {"awow", "A/v/U"},
  {"awwo", "A/w/(@)", "O/w/(@)"},
  {"awy", "A/w/i", "O/i"},
  {"awye", "O/j/@/r"},
  {"ay", "aI", "E/@", "E", "eI", "eI/@", "i"},
  {"aya", "A/j/@", "A/j/A", "eI/&", "eI/@", "aI/@", "aI/j/A", "@/j/A", "aI/A", 
    "j/@", "eI/j/@"},
  {"aye", "A/j/E", "eI", "A/i", "@/j/eI", "eI/@"},
  {"ayeau", "A/j/U"},
  {"ayee", "eI/i"},
  {"ayey", "A/j/E/i", "eI/i"},
  {"ayi", "A/j/I", "A/j/i"},
  {"ayo", "A/j/A", "A/j/O", "A/j/oU", "aI/oU", "eI/@", "eI/A", "eI/j/oU", "eI/O",
    "eI/oU", "j/oU"},
  {"ayoja", "A/j/oU"},
  {"ayou", "eI/AU", "eI/j/u"},
  {"ayu", "A/j/u"},
  {"ayuo", "A/j/AU"},
  {"ayw", "eI"},
  {"aywa", "eI/w/&", "eI/w/@"},
  {"aywe", "eI/w"},
  {"aywee", "eI/w/i"},
  {"aywi", "eI/w/I", "eI/w/aI"},
  {"aywo", "eI/w/U", "eI/w/(@)"},
  {"aywoo", "eI/w/U"},
  {"ayya", "aI/j/&"},
  {"ayyi", "A/j/I"},

  {"'b", "b"},
  {"b'", "b"},
  {"b", "b", "p"},
  {"bb", "b"},
  {"bbr", "b/r"},
  {"bbs", "b/z"},
  {"bc", "b/k", "b/s"},
  {"bch", "b/tS"},
  {"bcl", "b/k/l"},
  {"bbl", "b/l"},
  {"bd", "b/d"},
  {"bdd", "b/d"},
  {"bdr", "b/d/r"},
  {"bf", "b/f"},
  {"bfl", "b/f/l"},
  {"bfr", "b/f/r"},
  {"bg", "b/g", "b/dZ"},
  {"bh", "b"},
  {"bk", "b/k"},
  {"bkh", "b/k", "b/x"},
  {"bkn", "p/k/n"},
  {"bl", "b/@/l", "b/l"},
  {"bm", "b/m"},
  {"bmh", "b/m"},
  {"bn", "b/@/n", "b/n"},
  {"b'n", "b/-/n"},
  {"bp", "b/p"},
  {"bpl", "b/p/l"},
  {"bq", "b/k"},
  {"br'", "b/r"},
  {"b'r", "b/r"},
  {"br", "b/r", "b/R"},
  {"brn", "b/(@)/r/n"},
  {"brz", "b/r/E/Z", "b/r/i/z", "b/Z"},
  {"b's", "b/z"},
  {"bs", "b/s", "b/z"},
  {"bsc", "b/s", "b/s/k"},
  {"bscr", "b/s/k/r"},
  {"bsh", "S/i", "S/aI"},
  {"bsk", "p/s/k"},
  {"bsl", "b/s/l"},
  {"bsp", "b/s/p"},
  {"bst", "b/s/t"},
  {"bstr", "b/s/t/r"},
  {"bt", "b/t", "t"},
  {"btf", "t/f"},
  {"btl", "t/-/l"},
  {"btr", "b/t/r"},
  {"bts", "p/t/s"},
  {"bv", "b/v"},
  {"bz", "b/z"},

  {"'c", "k"},
  {"c'", "s"},
  {"c", "k", "s", "S", "tS", "t/s"},
  {"cb", "k/b"},
  {"cc", "k", "k/s", "tS"},
  {"cch", "k", "t/tS"},
  {"cf", "k/f"},
  {"cfl", "k/f/l"},
  {"ch", "k", "h", "tS", "S"},
  {"ck", "k"},
  {"cl", "k/l"},
  {"ccl", "k/l"},
  {"ccr", "k/r"},
  {"cd", "k/d"},
  {"ch'", "tS"},
  {"ch", "dZ", "k", "tS", "x"},
  {"chb", "tS/b"},
  {"chbl", "tS/b/l"},
  {"chc", "tS/k"},
  {"chch", "k/tS", "tS"},
  {"chcl", "tS/k/l"},
  {"chcr", "tS/k/r"},
  {"chd", "tS/d"},
  {"chdr", "tS/d/r"},
  {"chf", "tS/f"},
  {"chh", "k/h", "tS/h"},
  {"chk", "tS/k", "s/k"},
  {"chl", "k/l", "tS/l"},
  {"chm", "k/m", "x/m", "m"},
  {"chn", "k/n", "S/n", "tS/n"},
  {"chp", "x/p"},
  {"chr", "k/r", "k/@/r", "k/R"},
  {"chs", "k/s"},
  {"chsb", "k/s/b"},
  {"chsf", "x/S/f"},
  {"chsh", "k/s", "x/S"},
  {"chsm", "k/s/m"},
  {"chst", "k/s/t", "tS/s/t"},
  {"chsth", "k/s/t"},
  {"chstr", "k/S/t/r"},
  {"cht", "k/t", "s/t", "S/t", "t", "x/t"},
  {"chth", "k/T", "T", "x/t/h"},
  {"chtl", "tS/t/l"},
  {"chtp", "x/t/p"},
  {"chts", "t/s"},
  {"chtsm", "t/s/m"},
  {"chz", "x/z"},
  {"ckb", "k/b"},
  {"ckbl", "k/b/l"},
  {"ckbr", "k/b/r"},
  {"ckc", "k/k", "k"},
  {"ckch", "k/tS"},
  {"ckcl", "k/k/l"},
  {"ckcr", "k/k/r"},
  {"ckd", "k/d"},
  {"ckdr", "k/d/r"},
  {"ckf", "k/f"},
  {"ckfl", "k/f/l"},
  {"ckfr", "k/f/r"},
  {"ckg", "k/g"},
  {"ckgr", "k/g/r"},
  {"ckh", "k", "k/h"},
  {"ckk", "k/k"},
  {"ckkn", "k/n"},
  {"ckl", "k/@/l", "k/l"},
  {"ckm", "k/m"},
  {"ckn", "k/n"},
  {"ckp", "k/p"},
  {"ckpl", "k/p/l"},
  {"ckpr", "k/p/r"},
  {"ckr", "k/r"},
  {"ck's", "k/s"},
  {"cks", "k/s"},
  {"cksb", "k/s/b"},
  {"cksc", "k/s/k"},
  {"cksf", "k/s/f", "k/s/&/f"},
  {"cksk", "k/s/k"},
  {"cksl", "k/s/l"},
  {"cksh", "k/S"},
  {"cksm", "k/s/m"},
  {"cksn", "k/s/n"},
  {"cksp", "k/s/p"},
  {"ckspl", "k/s/p/l"},
  {"ckscr", "k/s/k/r"},
  {"ckst", "k/s/t"},
  {"ckstr", "k/s/t/r"},
  {"cksv", "k/s/v"},
  {"ckt", "k/t"},
  {"ckth", "k/T"},
  {"ckthr", "k/T/r"},
  {"cktr", "k/t/r"},
  {"ckv", "k/f"},
  {"ckx", "k/s"},
  {"'cl", "k/l"},
  {"cl", "k/@/l", "k/l"},
  {"cm", "k/m"},
  {"cn", "k/n", "n"},
  {"cph", "k/f"},
  {"cq", "k"},
  {"cr", "k/r", "k/R"},
  {"'c's'l", "k/s"},
  {"cs", "k/s", "dZ", "tS"},
  {"csk", "tS/k"},
  {"cst", "k/s/t"},
  {"ct", "k/t", "k/tS", "k/S"},
  {"ctf", "k/t/f"},
  {"cth", "k/T"},
  {"cthl", "k/T/l"},
  {"ctl", "k/t/l"},
  {"ctm", "t/m"},
  {"ctn", "k/t/n"},
  {"ctr", "k/t/r"},
  {"cts", "k/t/s"},
  {"cv", "k/v", "s/v"},
  {"cz", "tS", "z"},
  {"czm", "S/m", "tS/m"},

  {"'d", "d"},
  {"d'", "d", "D"},
  {"d", "d", "t", "dZ", "T", ""},
  {"db", "d/b"},
  {"dbl", "d/b/l"},
  {"dbr", "d/b/r"},
  {"dc", "d/k"},
  {"dch", "d/tS"},
  {"dcl", "d/k/l"},
  {"dcr", "d/k/r"},
  {"dd", "d"},
  {"ddb", "d/b"},
  {"ddf", "d/f", "D/v"},
  {"ddh", "d"},
  {"ddl", "d/-/l", "d/@/l", "d/l"},
  {"ddm", "d/m"},
  {"ddr", "d/r"},
  {"dds", "d/s", "d/z"},
  {"df", "d/f"},
  {"dfl", "d/f/l"},
  {"dfr", "d/f/r"},
  {"dg", "dZ", "d/g"},
  {"dgl", "dZ/l"},
  {"dgm", "dZ/m"},
  {"dgr", "d/g/r"},
  {"dh", "d", "d/h", "D"},
  {"d'h", "d"},
  {"dhr", "d/r", "d/R"},
  {"dhp", "d/p"},
  {"dk", "d/k"},
  {"dl", "d/-/l", "d/@/l", "d/l"},
  {"dm", "d/m"},
  {"dn", "d/n"},
  {"dn't", "d/-/n/t"},
  {"dp", "d/p"},
  {"dpl", "d/p/l"},
  {"dq", "d/k"},
  {"dpr", "d/p/r"},
  {"dr", "d/r", "d/@/r", "d/R"},
  {"d's", "d/z"},
  {"ds", "d/s", "d/z"},
  {"dsb", "d/z/b"},
  {"dsc", "d/s"},
  {"dscr", "d/s/k/r"},
  {"dsd", "d/z/d"},
  {"dsf", "d/z/f"},
  {"dsh", "d/S", "t/s/h"},
  {"dsk", "d/s/k", "t/s/k"},
  {"dsl", "d/s/l"},
  {"dsm", "d/z/m"},
  {"dsp", "d/s/p"},
  {"dspr", "d/s/p/r"},
  {"dst", "d/s/t"},
  {"dstr", "d/s/t/r"},
  {"dt", "d/t", "t"},
  {"dth", "d/T", "t/h"},
  {"dv", "d/v"},
  {"dz", "dZ", "d/z"},
  {"dzh", "dZ", "d/Z", "Z"},

  {"e", "eI", "I", "E", "@", "i", "-", "A", "(@)", "j/E", ""},
  {"ea", "(@)", "&", "A", "E", "eI", "i", "j/@", "O", "i/@", "eI/A", "eI/@",
    "I/j/@", "j/A", "j/I"},
  {"eau", "oU", "y"},
  {"ee", "i", "eI", "@", "E", "i/E", "i/@", "i/I"},
  {"eeuw", "u"},
  {"ej", "E/dZ", "E/z", "E/Z"},
  {"eja", "i/dZ/&", "eI/Z/A", "eI/@"},
  {"eje", "eI/h/eI", "I/dZ/E", "E/dZ/@"},
  {"eji", "E/dZ/i", "I/dZ/aI"},
  {"ejo", "eI/h/oU", "eI/oU", "i/dZ/Oi"},
  {"eju", "E/dZ/@", "eI/dZ/u", "eI/Z/U", "I/dZ/u"},
  {"ei", "@", "aI", "E", "eI", "i", "I", "i/I"},
  {"eio", "eI/O", "i/@", "i/aI", "I/j/oU", "aI/oU", "aI/A"},
  {"eo", "eI/oU", "i/@", "i/oU", "E/O"},
  {"eoi", "i/Oi", "i/oU"},
  {"eou", "@", "A", "AU", "i/@"},
  {"eu", "i/j/u", "E/U", "j/u", "y"},
  {"eui", "-"},
  {"ew", "h/j/u", "j/u", "u", "E/f"},
  {"ewa", "eI/w/A"},
  {"eway", "w/eI"},
  {"ewe", "j/u/@", "j/u/E", "j/u", "w/E", "@/w/E", "u/@", "u", "u/E", "u/I"},
  {"ewee", "w/i"},
  {"ewi", "eI/w/i", "i/w/aI", "I/w/I", "i/w/I", "j/u/I", "u/I"},
  {"ewo", "w/(@)", "w/oU", "w/U", "w/oU"},
  {"ey", "eI", "i", "aI"},
  {"eya", "@", "A", "aI/@", "E/j/A", "eI/@", "eI/j/A", "i/@", "j/A"},
  {"eye", "aI", "aI/@"},
  {"eyo", "aI/@", "eI/@", "eI/oU", "i/A"},
  {"eywo", "i/w/(@)"},

  {"'f", "f"},
  {"f", "f", "v"},
  {"fb", "f/b"},
  {"fc", "f/k"},
  {"fd", "f/d", "f/t"},
  {"ff", "f"},
  {"ffb", "f/b"},
  {"ffc", "f/k"},
  {"ffch", "f/tS"},
  {"ffh", "f/h"},
  {"ffk", "f/k"},
  {"ffl", "f/l", "f/@/l"},
  {"ffm", "f/m"},
  {"ffn", "f/n"},
  {"ffpr", "f/p/r"},
  {"ffr", "f/r"},
  {"ffs", "f/s"},
  {"ffsc", "f/s/k"},
  {"ffscr", "f/s/k/r"},
  {"ffsh", "f/S"},
  {"ffspr", "f/s/p/r"},
  {"ffst", "f/s/t"},
  {"fft", "f/t"},
  {"fg", "f/g"},
  {"fgh", "f/g"},
  {"fh", "f/h"},
  {"fk", "f/k"},
  {"fl", "f/l"},
  {"fm", "f/m"},
  {"fn", "f/n", "v/@/n"},
  {"fr", "f/r", "f/R"},
  {"fs", "f/s"},
  {"fsk", "f/s/k"},
  {"fss", "f/s"},
  {"fst", "f/s/t"},
  {"ft", "f/t"},
  {"ftb", "f/t/b"},
  {"ftf", "f/t/f"},
  {"fth", "f/T"},
  {"fthl", "f/T/l"},
  {"ftl", "f/t/l"},
  {"ftm", "f/t/m"},
  {"ftp", "f/t/p"},
  {"ftpr", "f/t/p/r"},
  {"fts", "f/t/s"},
  {"ftsh", "f/t/S"},
  {"ftsm", "f/t/s/m"},
  {"ftt", "f/t/t"},
  {"fz", "f/z"},

  {"g", "g", "dZ", "Z", "g/j", "x"},
  {"gb", "g/b"},
  {"gc", "dZ"},
  {"gd", "g/d"},
  {"gf", "g/f"},
  {"gfl", "g/f/l"},
  {"gg", "g", "dZ", "k"},
  {"ggb", "g/b"},
  {"ggc", "g/k"},
  {"ggcr", "g/k/r"},
  {"ggdr", "g/d/r"},
  {"ggl", "g/-/l", "g/@/l", "g/l"},
  {"ggpl", "g/p/l"},
  {"ggr", "g/r"},
  {"ggs", "g/z"},
  {"ggsh", "g/S"},
  {"gh", "g", "x", "f", ""},
  {"ghb", "b"},
  {"ghd", "g/d"},
  {"ghl", "g/l"},
  {"ght", "t", "x/t", "f/t"},
  {"ghtb", "f/t/b", "t/b"},
  {"ghtc", "t/k"},
  {"ghtcl", "t/k/l"},
  {"ghtdr", "t/d/r"},
  {"ghtf", "t/f"},
  {"ghtg", "t/g"},
  {"ghth", "t/h"},
  {"ghthl", "t/T/l"},
  {"ghtl", "t/l"},
  {"ghtm", "t/m"},
  {"ghtn", "t/n"},
  {"ghtp", "t/p"},
  {"ghtr", "t/r"},
  {"ghts", "t/s", "f/t/s"},
  {"gl", "g/l", "g/@/l"},
  {"gm", "g/m", "m"},
  {"gn", "g/n", "n"},
  {"gnm", "n/m"},
  {"gp", "g/p"},
  {"gr", "g/r"},
  {"g's", "g/z"},
  {"gs", "g/z", "g/s"},
  {"gsb", "g/z/b", "x/S/b"},
  {"gsh", "g/S", "g/s", "k/s/h"},
  {"gsk", "g/s/k"},
  {"gsm", "g/z/m"},
  {"gsp", "g/s/p"},
  {"gst", "g/s/t"},
  {"gt", "g/t"},
  {"gth", "g/T"},
  {"gtr", "g/t/r"},
  {"gv", "g/v"},
  {"gz", "g/z"},

  {"h", "h", ""},
  {"hd", "d"},
  {"hf", "f"},
  {"hg", "r"},
  {"hh", "h"},
  {"hl", "l"},
  {"hm", "m"},
  {"hn", "n"},
  {"hnn", "n"},
  {"hns", "n/s", "n/z"},
  {"hr", "r", "R"},
  {"hs", "S", "z"},
  {"ht", "t"},
  {"hv", "k/v", "v", "x/v"},
  {"hz", "z"},

  {"i", "i", "I", "@", "(@)", "aI", "E", "j/i"},
  {"ia", "@", "i/&", "i/@", "i/A", "i", "j/A", "j/@", "aI/@", "j/U", "A", "eI", 
    "I/A", "I", "i/j/A", "i/E"},
  {"iau", "i/AU", "i/O", "i/oU", "j/A", "j/oU", "j/u", "aI/O"},
  {"iae", "i/@"},
  {"iao", "A/O", "i/O", "j/AU"},
  {"iaye", "i", "aI/j/E"},
  {"ie", "i", "j/(@)", "aI", "eI", "I", "j/@", "E", "aI/i", "i/@", "i/&", "i/E",
    "aI/I", "aI/@", "-", "@"},
  {"ieu", "j/y", "u"},
  {"iew", "j/u"},
  {"ii", "i", "i/I", "i/i"},
  {"ij", "aI", "eI", "I"},
  {"ija", "aI/dZ/&", "i/@", "i/j/A"},
  {"ije", "aI/dZ/E", "@/dZ/E", "i/E"},
  {"ijo", "i/Z/O", "I/dZ/A", "i/dZ/oU", "i/h/O", "i/h/oU", "i/oU"},
  {"io", "i/O", "i/oU", "j/@", "j/oU", "I/oU", "oU", "aI/oU", "j/O", "i/@", "O"},
  {"ioa", "aI/oU", "j/O/A", "i/oU"},
  {"ioe", "aI/i", "aI/oU", "aI/E", "aI/i", "i/i"},
  {"ioi", "aI/Oi", "aI/oU", "i/Oi"},
  {"iou", "i/u"},
  {"iu", "@", "u", "j/u", "aI/j/u", "i/U", "i/u"},
  {"iuo", "i/u/oU"},
  {"iwe", "i/w/eI"},
  {"iwiye", "i/w/i/j/@"},
  {"iy", "aI/I", "i/I"},
  {"iya", "i/j/&", "i/j/@", "i/j/A", "i/j/O"},
  {"iyaa", "i/j/A"},
  {"iye", "i/@"},

  {"j", "dZ/u", "dZ/eI", "j/-"},
  {"ja", "&", "dZ/&", "dZ/A", "dZ/eI", "Z/A", "d/j/@", "dZ/@", "j/A"},
  {"jaa", "dZ/@"},
  {"jae", "dZ/eI", "h/A/E", "j/eI", "S/E"},
  {"jai", "aI", "h/aI"},
  {"jau", "dZ/A", "dZ/O", "j/AU", "j/oU", "Z/O", "Z/oU"},
  {"jaw", "dZ/O", "j/AU"},
  {"jay", "dZ/eI"},
  {"jaya", "dZ/A/j/A"},
  {"je", "dZ/@", "dZ/E", "j/eI", "i", "dZ/i", "j/@", "j/E", "E"},
  {"jea", "Z/A", "dZ/i"},
  {"jee", "dZ/i"},
  {"jeju", "dZ/I/dZ/u"},
  {"jeo", "dZ/E"},
  {"jeu", "Z/y"},
  {"jew", "dZ/u"},
  {"jewe", "dZ/u/@", "dZ/u/I"},
  {"ji", "dZ/i", "dZ/I", "j/i"},
  {"jiji", "dZ/I/dz/i"},
  {"jo", "dZ/A", "dZ/O", "dZ/oU", "h/O", "h/oU", "oU", "j/O"},
  {"joa", "dZ/oU", "h/w/A", "j/oU/A", "j/oU", "Z/O"},
  {"joao", "dZ/oU/A/oU"},
  {"joi", "dZ/Oi", "Z/@", "Z/w/&"},
  {"joo", "j/u"},
  {"jou", "dZ/(@)", "dZ/AU", "dZ/u", "j/AU", "Z/u"},
  {"joy", "dZ/Oi"},
  {"ju", "dZ/U", "dZ/u"},
  {"jua", "h/w/A", "w/A", "Z/w/A"},
  {"jui", "dZ/u", "w/i", "Z/w/E"},
  {"juju", "dZ/u/dZ/u"},
  {"jwa", "i/w/A"},
  {"jy", "dZ/I", "j/Y"},

  {"'k", "k"},
  {"k'", "k"},
  {"k", "k", "g", "tS"},
  {"kb", "k/b"},
  {"kch", "k/tS"},
  {"kd", "k/d"},
  {"kf", "k/f"},
  {"kfr", "k/f/r"},
  {"kh", "k/h", "k", "x"},
  {"khb", "k/b"},
  {"khl", "x/l"},
  {"khm", "k/m"},
  {"khn", "k/n", "x/n"},
  {"khr", "k/r"},
  {"khsh", "x/S"},
  {"kht", "x/t"},
  {"khz", "k/z"},
  {"kk", "k"},
  {"kkr", "k/r"},
  {"kl", "k/l"},
  {"km", "k/m"},
  {"kn", "n", "k/n"},
  {"kp", "k/p"},
  {"kr", "k/r", "k/@/r"},
  {"ks", "k/s"},
  {"ksh", "k/S"},
  {"kshm", "k/S/m"},
  {"ksk", "k/s/k"},
  {"ksp", "k/s/p"},
  {"kst", "k/s/t"},
  {"kt", "k/t"},
  {"kthr", "k/T/r"},
  {"kv", "k/v"},

  {"l'", "l"},
  {"l", "l"},
  {"lb", "l/b"},
  {"lbl", "l/b/l"},
  {"lbr", "l/b/r", "l/b/R"},
  {"lc", "l/k", "l/s", "l/S"},
  {"lch", "l/tS", "l/k"},
  {"lcl", "l/k/l"},
  {"lcm", "l/k/m"},
  {"lcr", "l/k/r"},
  {"lcz", "l/tS"},
  {"ld", "l/d", "l/t"},
  {"ldb", "l/d/b"},
  {"ldc", "l/d/k"},
  {"ldcr", "l/d/k/r"},
  {"ldf", "l/d/f"},
  {"ldh", "l/d/h", "l/d"},
  {"ldl", "l/d/l"},
  {"ldm", "l/d/m"},
  {"ldn", "l/d/n"},
  {"ldp", "l/d/p"},
  {"ldr", "l/d/r", "l/d/@/r"},
  {"lds", "l/d/z", "l/d/s"},
  {"ldsm", "l/d/z/m", "l/d/s/m"},
  {"ldsp", "l/d/s/p"},
  {"ldst", "l/d/s/t"},
  {"ldt", "l/t"},
  {"ldv", "l/d/v"},
  {"lf", "l/f", "f"},
  {"lfc", "l/f/k"},
  {"lfl", "l/f/l"},
  {"lfp", "l/f/p"},
  {"lfr", "l/f/r", "l/f/R"},
  {"lfs", "l/f/s"},
  {"lft", "l/f/t"},
  {"lg", "l/dZ", "l/g", "l/@/g"},
  {"lgh", "l/g"},
  {"lgr", "l/g/r", "l/g/R"},
  {"lh", "l"},
  {"l'h", "l"},
  {"lk", "l/k", "k"},
  {"lkh", "l/k", "k"},
  {"lkm", "l/k/m", "k/m"},
  {"ll", "l"},
  {"'ll", "l"},
  {"llb", "l/b"},
  {"llbl", "l/b/l"},
  {"llbr", "l/b/r"},
  {"llc", "l/k"},
  {"llcl", "l/k/l"},
  {"lld", "l/d"},
  {"lldr", "l/d/r"},
  {"llf", "l/f"},
  {"llfl", "l/f/l"},
  {"llfr", "l/f/r"},
  {"llg", "l/dZ"},
  {"llgr", "l/g/r"},
  {"llh", "l/h"},
  {"llk", "l/k"},
  {"llm", "l/m"},
  {"lln", "l/n"},
  {"llp", "l/p"},
  {"llph", "l/f"},
  {"llpl", "l/p/l"},
  {"llpr", "l/p/r"},
  {"llr", "l/r", "l/R"},
  {"lls", "l/z"},
  {"llst", "l/s/t"},
  {"llstr", "l/s/t/r"},
  {"lm", "l/m", "m"},
  {"ln", "l/n", "l", "n"},
  {"lp", "l/p"},
  {"lph", "l/f"},
  {"lpl", "l/p/l"},
  {"lpm", "l/p/m"},
  {"lpr", "l/p/r"},
  {"lps", "l/p/s"},
  {"lpt", "l/p/t", "l/p/tS"},
  {"lq", "l/k"},
  {"lr", "l/r"},
  {"ls", "l/s", "l/S", "l/z"},
  {"lsh", "l/S"},
  {"lsk", "l/s/k"},
  {"lsm", "l/z/m"},
  {"l's", "l/z"},
  {"lst", "l/s/t"},
  {"lt", "l/t"},
  {"lth", "l/T", "l/t/h"},
  {"ltl", "l/t/l"},
  {"ltr", "l/t/r"},
  {"lv", "l/v"},
  {"lz", "l/z", "l/t/s"},

  {"'m", "m"},
  {"m", "m"},
  {"mb", "m/b", "m"},
  {"mbd", "m/d"},
  {"mbf", "m/f"},
  {"mbk", "m/k"},
  {"mbl", "m/b/@/l", "m/b/l"},
  {"mbm", "m/m"},
  {"mbn", "m/n"},
  {"mbpr", "m/p/r"},
  {"mbr", "m/b/r"},
  {"mbs", "m/z", "m/s"},
  {"m'b", "m/b"},
  {"mc", "m/s"},
  {"mcc", "m/@/k"},
  {"mccl", "m/@/k/l"},
  {"mccr", "m/@/k/r"},
  {"mcd", "m/@/k/d"},
  {"mcf", "m/@/k/f"},
  {"mcg", "m/@/g", "m/I/g"},
  {"mch", "m/tS"},
  {"mck", "m/@/k"},
  {"mcgr", "m/@/g/r"},
  {"mcm", "m/@/k/m"},
  {"mcn", "m/@/k/n"},
  {"mcr", "m/@/k/r", "m/k/r"},
  {"mcsh", "m/@/k/S"},
  {"mct", "m/@/t"},
  {"md", "m/d"},
  {"mdl", "m/d/l"},
  {"mdn", "m/d/n"},
  {"mdr", "m/d/r"},
  {"mf", "m/f"},
  {"mfl", "m/f/l"},
  {"mfr", "m/f/r", "m/f/R"},
  {"mg", "m/dZ", "m/g"},
  {"mk", "m/k"},
  {"ml", "m/l"},
  {"mh", "m/h"},
  {"mm", "m"},
  {"mn", "m/n"},
  {"mp", "m/p"},
  {"mph", "m/f"},
  {"mpk", "m/p/k"},
  {"mpl", "m/p/l", "m/p/@/l"},
  {"mps", "m/p/s"},
  {"mpr", "m/p/r"},
  {"mpt", "m/p/t"},
  {"mr", "m/r"},
  {"ms", "m/s", "m/z"},
  {"msh", "m/S"},
  {"msl", "m/s/l"},
  {"msp", "m/s/p"},
  {"mst", "m/s/t"},
  {"mt", "m/t"},

  {"'n", "n"},
  {"n", "n", "N", "n/j"},
  {"nb", "n/b"},
  {"nbl", "n/b/l"},
  {"nbr", "n/b/r"},
  {"nc", "n/k", "N/k"},
  {"nch", "n/tS", "N/k"},
  {"ncl", "n/k/l"},
  {"ncr", "n/k/r"},
  {"nct", "n/k/S", "n/k/t"},
  {"nd", "n/d", "N"},
  {"n'd", "n/dZ"},
  {"nddr", "n/d/r"},
  {"ndl", "n/d/-/l", "n/d/@/l", "n/d/l"},
  {"ndh", "n/t/h"},
  {"ndm", "n/d/m", "n/m"},
  {"ndn", "n/d/n", "n/n"},
  {"ndr", "n/d/r"},
  {"nds", "n/d/s", "n/d/z"},
  {"ndv", "n/d/w"},
  {"nf", "n/f"},
  {"nfl", "n/f/l"},
  {"nfr", "n/f/r"},
  {"ng", "n/dZ", "N/d", "N", "N/g", "n/g"},
  {"ngb", "N/b"},
  {"ngc", "N/k"},
  {"ngd", "N/d"},
  {"ngf", "N/f"},
  {"ngk", "N/k"},
  {"ngg", "N/g"},
  {"ngh", "N/g"},
  {"ngl", "N/g/@/l", "N/g/l", "N/l"},
  {"ngn", "N/n"},
  {"ngr", "n/g/r", "N/g/r"},
  {"ngs", "N/z", "N/s"},
  {"ngsh", "N/S"},
  {"ngst", "N/s/t"},
  {"ngstr", "N/s/t/r"},
  {"ngt", "N/t"},
  {"ngz", "N/z"},
  {"nh", "n/j", "N"},
  {"nk", "N/k", "n/k"},
  {"nkf", "N/k/f"},
  {"nkg", "N/k/g"},
  {"nkh", "N/k/h"},
  {"nkl", "N/k/l", "N/k/@/l"},
  {"nkr", "n/k/r"},
  {"nl", "n/l"},
  {"nm", "n/m"},
  {"nn", "n"},
  {"np", "n/p"},
  {"npl", "n/p/l"},
  {"npr", "n/p/r"},
  {"nq", "N/k"},
  {"nr", "n/r", "n/R"},
  {"ns", "n/s", "n/z", "N"},
  {"nsb", "n/z/b"},
  {"nsc", "n/s", "n/S", "n/s/k"},
  {"nsch", "n/S", "n/s"},
  {"nscr", "n/s/k/r", "n/s/k/R"},
  {"nsf", "n/s/f", "n/z/f"},
  {"nsh", "n/S"},
  {"nsk", "n/s/k"},
  {"nsl", "n/s/l", "n/z/l"},
  {"nsm", "n/s/m", "n/z/m"},
  {"nsp", "n/s/p"},
  {"nss", "n/s", "n/z"},
  {"nst", "n/s/t"},
  {"nstr", "n/s/t/r"},
  {"nsv", "n/s/v", "n/z/v"},
  {"nt", "n/t", "N/t", "N"},
  {"n't", "n/t"},
  {"nth", "n/T"},
  {"nthr", "n/T/r"},
  {"ntl", "n/t/l"},
  {"ntr", "n/t/r"},
  {"nts", "n/t/s"},
  {"nv", "n/v"},
  {"nx", "N/k/s"},
  {"nz", "n/z"},

  {"o", "A", "oU", "O", "@", "u", "U", "j/oU", "y"},
  {"oa", "oU/@", "oU/A", "oU", "O/A", "w/A", "oU/&"},
  {"oe", "oU", "U", "u", "oU/E"},
  {"oeu", "(@)", "i/@", "oU/i", "u", "y", "Y"},
  {"oi", "oU/i", "w/A", "Oi"},
  {"oia", "O/j/A", "Oi/@", "Oi/A", "oU/aI"},
  {"oji", "oU/dZ/I"},
  {"oo", "u", "oU"},
  {"ou", "u", "w/A", "AU", "@"},
  {"oua", "U/A", "u/A", "w/A"},
  {"oue", "w/@", "w/i"},
  {"oui", "u/I", "u/i"},
  {"ouj", "u/dZ"},
  {"ow", "AU", "oU"},
  {"owa", "U/w/A"},
  {"owe", "oU/@", "oU/w/E", "A/w", "AU", "oU", "AU/@"},
  {"owi", "oU/I", "oU/aI", "oU/v/I", "oU/w/aI", "oU/w/I"},
  {"owo", "oU/w/A", "oU/w/oU"},
  {"oy", "Oi", "y/i"},
  {"oya", "Oi/@", "Oi/A", "O/j/A", "Oi/&", "w/A/j/A", "oU/j/A"},
  {"oye", "OI/j/E", "O/j/E", "Oi/@", "Oi", "Oi/j/(@)"},
  {"oyo", "O/j/O"},
  {"oyu", "O/j/u", "oU/j/u"},

  {"p", "p"},
  {"pb", "p/b", "b"},
  {"pc", "p/k"},
  {"pch", "p/tS"},
  {"pd", "p/d"},
  {"pf", "p/f", "f"},
  {"ph", "f", "p"},
  {"phl", "f/l"},
  {"phr", "f/r"},
  {"phth", "f/T", "T"},
  {"pk", "p/k"},
  {"pl", "p/l"},
  {"pm", "p/m"},
  {"pn", "n"},
  {"pp", "p"},
  {"ppl", "p/l"},
  {"ppr", "p/r"},
  {"pr", "p/r"},
  {"ps", "p/s", "s"},
  {"psh", "p/S"},
  {"pst", "p/s/t"},
  {"pt", "p/S", "p/t"},
  {"ptr", "p/t/r"},

  {"q", "k"},
  {"qb", "k/b"},
  {"qs", "k/s"},

  {"r", "r", "R", ""},
  {"rb", "r/b"},
  {"rbl", "r/b/@/l", "r/b/l"},
  {"rbr", "r/b/r"},
  {"rc", "r/k", "R/k"},
  {"rch", "r/k", "R/S", "r/tS", "r/S"},
  {"rcl", "r/k/l"},
  {"rcr", "r/k/r"},
  {"rct", "r/k/t"},
  {"rd", "r/d", "R", "R/d"},
  {"rdb", "r/d/b"},
  {"rdc", "r/d/k"},
  {"rdh", "r/d/h"},
  {"rdl", "r/d/l", "r/d/-/l"},
  {"rdm", "r/d/m"},
  {"rdn", "r/d/n"},
  {"rdr", "r/d/r", "R/d/R"},
  {"rds", "r/d/z", "r/d/s"},
  {"rf", "r/f"},
  {"rfl", "r/f/l"},
  {"rg", "r/g", "r"},
  {"rgh", "r/g"},
  {"rgl", "r/g/l"},
  {"rgt", "r/g/r"},
  {"rh", "r/h", "r"},
  {"rk", "r/k"},
  {"rkl", "r/k/l"},
  {"rks", "r/k/s"},
  {"rl", "r/l", "R/l"},
  {"rm", "r/m"},
  {"rml", "r/m/l"},
  {"rn", "r/n", "R/n"},
  {"rns", "r/n/z", "r/n/s"},
  {"rp", "r/p"},
  {"rph", "r/f"},
  {"rpl", "r/p/l"},
  {"rpr", "r/p/r"},
  {"rps", "r/p/s"},
  {"rq", "r/k"},
  {"rr", "r", "R"},
  {"rrh", "r"},
  {"rs", "r/s", "r/z", "R/s", "r"},
  {"rsc", "r/s/k"},
  {"rsd", "r/z/d"},
  {"rsh", "r/S"},
  {"rsk", "r/s/k", "R/s/k"},
  {"rsl", "r/s/l"},
  {"rsp", "r/s/p"},
  {"rsr", "r/z/r"},
  {"rst", "r/s/t"},
  {"rt", "r/t", "R/t", "R"},
  {"rtf", "r/t/f"},
  {"rth", "r/T", "r/t"},
  {"rthn", "r/T/n"},
  {"rthp", "r/T/p"},
  {"rtm", "r/t/m"},
  {"rtn", "r/t/n"},
  {"rtr", "r/t/r"},
  {"rts", "r/t/s"},
  {"rtsh", "r/t/S"},
  {"rthr", "r/T/r"},
  {"rtl", "r/t/l", "r/t/-/l"},
  {"rv", "r/v"},
  {"rz", "r/s", "r/z"},

  {"'s", "z"},
  {"s'", "z"},
  {"s", "s", "S", "z", "Z", ""},
  {"sb", "Z/b", "z/b"},
  {"sbr", "s/b/r", "z/b/r"},
  {"sc", "s/k"},
  {"sch", "s/k", "S"},
  {"schb", "S/b"},
  {"schk", "S/k"},
  {"schl", "S/l"},
  {"schm", "S/m"},
  {"schn", "S/n"},
  {"schr", "s/k/r", "S/r", "S/R"},
  {"schsch", "S/k"},
  {"schv", "S/v"},
  {"scl", "s/k/l", "s/@/l"},
  {"scr", "s/k/r", "s/k/R"},
  {"sd", "s/d", "z/d"},
  {"sdr", "s/d/r", "z/d/r"},
  {"sf", "s/f", "z/f"},
  {"sfl", "s/f/l", "z/f/l"},
  {"sfr", "s/f/r"},
  {"sg", "s/g"},
  {"sgl", "s/g/l"},
  {"sgn", "s/n"},
  {"sgr", "s/g/r", "s/k/r", "z/d/r"},
  {"sh", "S"},
  {"shb", "S/b"},
  {"shc", "S/k"},
  {"shd", "S/t"},
  {"shf", "S/f"},
  {"shg", "S/g"},
  {"shh", "S/h", "S"},
  {"shk", "S/k"},
  {"shl", "S/l"},
  {"shm", "S/m"},
  {"shn", "S/n"},
  {"shp", "S/p"},
  {"shr", "S/r"},
  {"sht", "S/t"},
  {"shv", "S/f"},
  {"sk", "s/k"},
  {"skh", "s/k"},
  {"skm", "s/k/m"},
  {"skn", "s/n"},
  {"skr", "s/k/r", "s/k/@/R"},
  {"skt", "s/k/t"},
  {"skv", "s/k/v"},
  {"sl", "s/l"},
  {"sm", "z/@/m", "s/m"},
  {"sn", "s/n"},
  {"sp", "s/p"},
  {"sph", "s/f"},
  {"spl", "s/p/l"},
  {"spn", "s/p/n"},
  {"spr", "s/p/r"},
  {"spt", "s/p/t"},
  {"sq", "s/k"},
  {"sr", "s/r", "s/R", "z/r"},
  {"srh", "s/r"},
  {"ss", "s"},
  {"ssb", "s/b"},
  {"ssbl", "s/b/l"},
  {"ssc", "s/k"},
  {"ssh", "s/h", "S"},
  {"ssk", "s/k"},
  {"ssl", "s/l"},
  {"ssm", "s/m"},
  {"ssn", "s/n"},
  {"ssp", "s/p"},
  {"ssr", "s/r"},
  {"sst", "s/t"},
  {"st", "s/t"},
  {"stb", "s/t/b"},
  {"stc", "s/t/k"},
  {"stf", "s/t/f"},
  {"sth", "s/T"},
  {"sthm", "s/m", "z/m"},
  {"stl", "s/@/l", "s/t/l"},
  {"stm", "s/t/m"},
  {"stn", "s/t/n"},
  {"str", "s/t/r"},
  {"stv", "s/t/v"},
  {"sv", "s/v", "z/v", "s/f"},
  {"sz", "z", "S", "s"},
  {"szk", "S/k", "s/k"},
  {"szt", "s/t"},

  {"t'", "t", "d"},
  {"t", "t", "S", ""},
  {"tb", "t/b", "t/@/b", "t/i/b"},
  {"tbl", "t/b/l"},
  {"tbr", "t/b/r"},
  {"tbz", "t/b/z"},
  {"tc", "t/k"},
  {"tch", "tS"},
  {"tchb", "tS/b"},
  {"tchbl", "tS/b/l"},
  {"tchc", "tS/k"},
  {"tchcr", "tS/k/r"},
  {"tchd", "tS/d"},
  {"tchf", "tS/f"},
  {"tchfl", "tS/f/l"},
  {"tchk", "tS/k"},
  {"tchl", "tS/l"},
  {"tchm", "tS/m"},
  {"tchn", "tS/n"},
  {"tchp", "tS/p"},
  {"tchpl", "tS/p/l"},
  {"tchst", "tS/s/t"},
  {"tcht", "tS/t"},
  {"tcl", "t/k/l"},
  {"tcr", "t/k/r"},
  {"t'd", "t/@/d"},
  {"td", "t/d"},
  {"tdr", "t/d/r"},
  {"tf", "t/f"},
  {"tfl", "t/f/l"},
  {"tfr", "t/f/r"},
  {"tg", "t/g"},
  {"tgr", "t/g/r", "t/dZ"},
  {"th", "T", "t", "D", "h", "s"},
  {"thb", "D/b", "T/b"},
  {"thbr", "T/b/r"},
  {"thchl", "T/k/l"},
  {"thdr", "D/d/r"},
  {"thf", "D/f", "T/f"},
  {"thg", "T/g"},
  {"thh", "T/h", "D/h"},
  {"thl", "t/l"},
  {"thm", "D/m", "D/@/m", "T/m"},
  {"thn", "T/n"},
  {"thp", "T/p"},
  {"thpl", "T/p/l"},
  {"thpr", "T/p/r"},
  {"thr", "T/r"},
  {"ths", "T/s", "D/s", "D/z", "T/z"},
  {"thsh", "T/S"},
  {"thsp", "T/s/p"},
  {"thst", "T/s/t"},
  {"tht", "T/t"},
  {"tk", "t/k"},
  {"tkn", "t/n"},
  {"t'l", "t/@/l"},
  {"tl", "t/l", "t/@/l", "t/-/l"},
  {"tll", "t/j/E"},
  {"tm", "t/m"},
  {"tn", "t/n"},
  {"tp", "t/p"},
  {"tpl", "t/p/l"},
  {"tpr", "t/p/r"},
  {"tq", "t/k"},
  {"tr", "t/r", "t/@/r", "t/@/R"},
  {"t's", "t/s"},
  {"ts", "t/s", "z", "tS"},
  {"tsb", "t/s/b"},
  {"tscr", "t/s/k/r"},
  {"tsd", "t/s/d"},
  {"tsf", "t/s/f"},
  {"tsh", "tS/A"},
  {"tsch", "tS"},
  {"tsk", "t/s/k"},
  {"tsm", "t/s/m"},
  {"tsp", "t/s/p"},
  {"tspr", "t/s/p/r"},
  {"tst", "t/s/t"},
  {"tstr", "t/s/t/r"},
  {"tsv", "t/s/v"},
  {"tt", "t"},
  {"ttb", "t/b"},
  {"ttd", "t/d"},
  {"ttfr", "t/f/r"},
  {"ttg", "t/g"},
  {"tth", "t/T", "T"},
  {"ttl", "t/-/l", "t/l"},
  {"ttr", "t/r"},
  {"tts", "t/s"},
  {"ttsb", "t/s/b"},
  {"ttsbl", "t/s/b/l"},
  {"ttsm", "t/s/m"},
  {"ttst", "t/s/t"},
  {"ttstr", "t/s/t/r"},
  {"ttsv", "t/s/v"},
  {"ttv", "t/v"},
  {"tv", "v"},
  {"tz", "t/s"},
  {"tzb", "t/s/b"},
  {"tzg", "t/s/dZ"},
  {"tzh", "t/s/h"},
  {"tzk", "t/z/k", "t/s/k"},
  {"tzkr", "t/s/k/R"},
  {"tzl", "t/s/l"},
  {"tzn", "t/s/n"},
  {"tzp", "t/s/p", "t/z/p"},
  {"tzr", "t/s/r"},
  {"tzs", "t/s"},
  {"tzsch", "tS"},
  {"tzst", "t/s/s/t", "t/s/S/t"},
  {"tzt", "t/s/t"},
  {"tzv", "t/s/v"},

  {"u", "u", "U", "@", "(@)", "Y", "j/u", "oU"},
  {"ua", "w/A", "w/eI", "u/A", "u/@", "u/E", "u/&", "w/@", "j/u/@"},
  {"ue", "u", "w/E", "w/eI", "E", "eI", "@", "(@)", "j/u/@", ""},
  {"uee", "w/i"},
  {"ui", "u", "w/I", "w/i", "Y", "j/u/I", "j/u/aI", "@", "aI", "i", "I", "u/i",
    "u/I", "u/aI"},
  {"uia", "i/@"},
  {"uja", "u/Z/A"},
  {"ujiji", "u/dZ/i/dZ/i"},
  {"uju", "u/Z/U"},
  {"uo", "j/u/A", "j/u/oU", "oU", "u/@", "u/A", "u/oU", "w/A", "w/O", "u/O"},
  {"uou", "j/u/@", "u/@"},
  {"uu", "u/@", "u", "j/u/@"},
  {"uuo", "u/@"},
  {"uwa", "U/w/A"},
  {"uwai", "U/w/eI"},
  {"uwe", "u/w/E"},
  {"uwi", "u/w/i"},
  {"uwia", "u/i/@"},
  {"uy", "aI", "w/i"},
  {"uya", "aI/&"},
  {"uyu", "u/j/u"},

  {"v", "v", "f"},
  {"'v", "v"},
  {"vc", "v/t/s"},
  {"vd", "b/d", "v/d"},
  {"vg", "v/g"},
  {"vgr", "f/g/r"},
  {"vk", "f/k", "v/k"},
  {"vl", "v/l"},
  {"vlt", "v/-/l/t"},
  {"vn", "v/n"},
  {"vp", "f/p"},
  {"vr", "v/@/r", "v/r", "v/R"},
  {"vrd", "v/r/@/d"},
  {"vsk", "v/s/k", "f/s/k"},
  {"vst", "v/i/s/t"},
  {"vt", "v/t", "v/i/t", "f/t"},
  {"vtz", "f/t/s"},
  {"vv", "v"},
  {"vz", "v/z"},
  {"vzh", "v/Z"},

  {"w", "w/I", "w/i", "w/E/@", "w/aI", "w/aI/@", "w/A", "w/@", "w/(@)"},
  {"wa", "w/O", "w/A", "w/@", "w/eI"},
  {"waa", "v/a", "w/&", "w/O"},
  {"wae", "w/eI"},
  {"wai", "w/A/i", "w/aI", "w/E", "w/eI"},
  {"wau", "w/A", "w/O"},
  {"waw", "w/A", "w/AU"},
  {"way", "w/eI"},
  {"we", "w/i", "w/E", "w/eI", "w/@"},
  {"wea", "w/E/@", "w/E", "w/i"},
  {"wee", "w/i"},
  {"wei", "w/i", "w/eI"},
  {"weu", "w/i/u"},
  {"wey", "v/aI", "v/eI", "w/eI"},
  {"wi", "w/I", "w/aI", "w/@", "w/(@)", "v/I", "v/I", "w/i"},
  {"wia", "w/i/j/A"},
  {"wie", "v/aI", "v/i", "w/aI", "w/i"},
  {"wo", "w/oU"},
  {"woe", "w/oU", "v/@"},
  {"woo", "w/U", "w/oU"},
  {"wou", "w/AU", "w/oU", "w/U", "w/u"},
  {"wu", "w/u/A", "w/@", "v/U", "w/(@)", "w/u", "w/U"},
  {"wy", "w/aI", "w/I"},
  {"wya", "w/aI/@"},
  {"wye", "w/aI", "w/aI/@"},
  {"wyo", "w/aI/oU"},

  {"x", "z", "s", "S", "k/s", ""},
  {"xb", "k/s/b"},
  {"xbl", "k/s/b/l"},
  {"xbr", "k/s/b/r"},
  {"xc", "k/s/s", "k/s/k", "k/s"},
  {"xch", "k/s/tS"},
  {"xcl", "k/s/k/l"},
  {"xcr", "k/s/k/r"},
  {"xd", "k/s/d"},
  {"xf", "k/s/f"},
  {"xg", "k/s/g"},
  {"xgl", "k/s/g/l"},
  {"xgr", "k/s/g/r"},
  {"xh", "k/s/h", "k/s", "g/z"},
  {"xl", "k/s/l"},
  {"xm", "k/s/m"},
  {"xn", "k/s/n"},
  {"xp", "k/s/p"},
  {"xpl", "k/s/p/l"},
  {"xpr", "k/s/p/r"},
  {"xq", "k/s/k"},
  {"xr", "k/s/r"},
  {"xs", "k/s/s", "k/s"},
  {"xsc", "k/s"},
  {"xst", "k/s/s/t"},
  {"xt", "k/s/tS", "k/s/t"},
  {"xtb", "k/s/t/b"},
  {"xth", "k/s/T"},
  {"xthl", "k/s/T/l"},
  {"xtl", "k/s/t/l"},
  {"xtr", "k/s/t/r"},
  {"xv", "k/s"},

  {"y", "aI", "i", "I", "@", "-", "(@)", "j/i"},
  {"ya", "j/@", "j/A", "j/&", "I/j/A", "i/A", "i/@", "aI/@", "aI/A", "aI/&", "j/E"},
  {"yae", "aI/i", "h/aI/i", "j/i"},
  {"yaeu", "aI/i"},
  {"yai", "aI", "j/Oi"},
  {"yaju", "j/@"},
  {"yao", "j/O"},
  {"yaou", "j/A/u"},
  {"yau", "j/O", "i/O", "j/AU", "j/oU"},
  {"yaw", "j/O"},
  {"ye", "j/@", "j/E", "i", "i/E", "i/(@)", "aI/I", "aI/i", "aI/@", "aI"},
  {"yi", "j/I", "j/aI", "i/I", "aI/I"},
  {"yo", "j/oU", "j/U", "j/@", "i/oU", "i/A", "i/O", "aI/A", "aI/@", "j/A"},
  {"you", "j/u"},
  {"yu", "i/@", "i/j/U", "i/u", "j/U", "j/u", "Y/u"},

  {"z", "z", "t/s", "T", "s", "Z", ""},
  {"zb", "z/b"},
  {"zc", "z/k", "z/dZ", "s/k"},
  {"zd", "z/d"},
  {"zf", "z/f"},
  {"zg", "z/g"},
  {"zh", "Z", "dZ", "t/s", "S"},
  {"zhd", "Z/d"},
  {"zhk", "Z/k"},
  {"zhn", "Z/n"},
  {"zk", "z/k", "s/k"},
  {"zl", "z/l", "z/@/l"},
  {"zm", "z/m"},
  {"zn", "s/n", "z/n"},
  {"zp", "z/p"},
  {"zr", "z/R", "s/r"},
  {"zs", "Z"},
  {"zsv", "Z/v"},
  {"zt", "z/t"},
  {"zth", "z/T"},
  {"zv", "z/v", "t/s"},
  {"zz", "z", "tS", "t/s", "t/z", "d/z"},
  {"zzb", "z/b"},
  {"zzl", "z/l", "z/@/l"},
  {"zzm", "z/m"},

  {"'", ""}
};

const vector<string> Consonants =
{
  "b", "c", "d", "f", "g", "h", "k", "l", "m", 
  "n", "p", "q", "r", "s", "t", "v", "x", "z", "'"
};

const vector<string> Vowels =
{
  "a", "e", "i", "j", "o", "u", "w", "y"
};


Extract::Extract()
{
  Extract::reset();
  Extract::setTable();
}


Extract::~Extract()
{
}


void Extract::reset()
{
}


void Extract::setTable()
{
  for (unsigned i = 0; i < PartsList.size(); i++)
  {
    const auto& entry = PartsList[i];
    const string& part = entry[0];

    for (unsigned j = 1; j < entry.size(); j++)
      pronMap[part].push_back(entry[j]);
  }

  for (auto &entry: Consonants)
    isVowelMap[entry] = 0;

  for (auto &entry: Vowels)
    isVowelMap[entry] = 1;
}


string Extract::recurseMatch(
  const string& part,
  const string& pron,
  unsigned& lpron)
{
  auto it = pronMap.find(part);
  if (it == pronMap.end())
    return "part " + part + ", pron " + pron + ": no part\n";

  for (auto &candPron: it->second)
  {
    lpron = candPron.size();
    if (lpron == 0)
    {
      histoMap[part]["."]++;
      return "";
    }
    else if (lpron <= pron.size() && candPron == pron.substr(0, lpron))
    {
      // Found a match.  Skip over '/' in pron.
      histoMap[part][candPron]++;
      return "";
    }
  }

  return "part " + part + ", pron " + pron + ": no match\n";
}


string Extract::recurse(
  const string& word,
  const string& pron,
  const bool state)
{
// cout << "enter " << word << ", " << pron << endl;
  for (unsigned i = 0; i < word.size(); i++)
  {
// cout << "i " << i << endl;
    if (isVowelMap[word.substr(i, 1)] == state)
      continue;

    // Change from vowel streak to consonant streak or vice versa.
    const string part = word.substr(0, i);

    auto it = pronMap.find(part);
    if (it == pronMap.end())
      return "part " + part + ", pron " + pron + ": no part\n";
    
    string ret;
    for (auto &candPron: it->second)
    {
      const unsigned lpron = candPron.size();
      string candToLog = "";
      if (lpron == 0)
        candToLog = ".";
      else if (lpron <= pron.size() && candPron == pron.substr(0, lpron))
        candToLog = candPron;
      else
        continue;
// cout << "candidate " << candToLog << endl;

      if (lpron >= pron.size())
      {
// cout << "Used up pron\n";
        ret = recurse(word.substr(i), "", ! state);
        if (ret == "")
        {
          histoMap[part][candToLog]++;
          return "";
        }
      }
      else if (lpron == 0)
      {
// cout << "Empty pron\n";
        ret = recurse(word.substr(i), pron, ! state);
        if (ret == "")
        {
          histoMap[part][candToLog]++;
          return "";
        }
      }
      else
      {
// cout << "General pron\n";
        ret = recurse(word.substr(i), pron.substr(lpron+1), ! state);
        if (ret == "")
        {
          histoMap[part][candToLog]++;
          return "";
        }
      }
    }

    return ret;
  }

  // Last part of the word.
  unsigned lpron;
  return recurseMatch(word, pron, lpron);
}


void Extract::enter(
  const string& word,
  const string& pron)
{
  string wlower = word;
  toLower(wlower);

  if (wlower.size() == 0)
    return;
  else 
  {
    const string& r = Extract::recurse(wlower, pron, isVowelMap[wlower.substr(0, 1)]);
    if (r != "")
      cout << r;
      // cout << "FAIL " << word << ", " << pron << ":\n" << r << "\n";
  }
}


void Extract::print(const string& fname) const
{
  ofstream fout;
  fout.open(fname);
  fout.close();
}

